#!/usr/bin/perl

use 5.18.0;
use warnings;
use strict;
use autodie qw(:all);

use Readonly;
use Math::Random qw(random_uniform_integer);
use Time::HiRes qw(usleep);


Readonly my $RING_BITS      => 5;
Readonly my $FILL_DEGREE    => 0.9;
Readonly my $SLEEP_MS       => 300;

Readonly my $RING_SIZE      => 2**$RING_BITS;
Readonly my $NUM_PEERS      => $FILL_DEGREE * $RING_SIZE;
Readonly my $FIRST_PORT     => 20_000;

Readonly my $JAR_FILE   => "$ENV{HOME}/n/dDist/ex07/target/ex07-1.0-SNAPSHOT-jar-with-dependencies.jar";

# Start first peer
start_peer($RING_BITS, $FIRST_PORT);

# Start other peers
for my $port ( ($FIRST_PORT + 1) .. ($FIRST_PORT + $NUM_PEERS) ) {
    usleep($SLEEP_MS * 1000);
    my $connect_port = random_uniform_integer(1, $FIRST_PORT, $port - 1);
    say "Starting peer on port $port. Connecting to port $connect_port.";
    start_peer($RING_BITS, $port, 'localhost', $connect_port, '> /dev/null');
}

sub start_peer {
    system "java -jar $JAR_FILE @_ &";
}

# Ringbits 8, sleep 400_000: end at around 80
# Ringbits 6, sleep 400_000: end at around 60
# Ringbits 5, sleep 100_000: end at around 17
